# Generated by Django 2.2.5 on 2019-09-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Email', max_length=150)),
                ('full_name', models.CharField(help_text='Full Name', max_length=100)),
            ],
        ),
    ]
