# Generated by Django 2.2.5 on 2019-09-20 01:44

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='summary',
            field=wagtail.core.fields.RichTextField(default='Enter Summary Here'),
        ),
    ]
